# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  WEBAPP: petstore-ak-eastus   # Replace with your JBoss site's name
  GROUP: oss-hack  # Replace with the resource group containing your JBoss EAP site
  SCRIPTS_DIR: 3A-postgresql  # Replace this with 3B-mysql or 3C-sql if you used MySQL or SQL
  
